Repository WildCodeSchool/orleans-0219-php-depot-vente-bannier, pull requests merged in 2019-04, with the labels that each got.

#1 install simple MVC
  .gitignore
  composer.lock
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#14 Sprint01 us02 jumbotron
  public/assets/css/style.css
  public/assets/images/jumbotron-furniture.png
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#15 Sprint01 us01 navbar
  .gitignore
  public/assets/css/style.css
  public/assets/images/logo.png
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#35 Sprint02 us08 selections categories
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/CategoriesManager.php
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#43 Sprint02 us09 gestion categories
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/categories.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#51 Sprint02 fix01
  src/Controller/HomeController.php
  src/Model/CategoriesManager.php
  src/View/Home/index.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#54 Sprint01 us03 footer
  composer.lock
  public/assets/css/style.css
  src/View/Item/_footer.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#52 Sprint02 us4 card
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/_card.html.twig
Labels: Reviewed by PO

#57 Sprint02 us10 gestion produits
  public/assets/css/style.css
  public/assets/images/delete-filled.png
  public/assets/images/edit-filled.png
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/products.html.twig
  src/View/_adminNavbar.html.twig
  src/View/adminLayout.html.twig
Labels: Corrections done, Reviewed by PO

#60 Sprint02_11_add categories list on the navbar's dropdown
  public/assets/css/style.css
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#62 Sprint02 us05 formulaire contact accueil
  composer.json
  composer.lock
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/View/Home/index.html.twig
  src/View/Item/_formContact.html.twig
  src/View/Item/emailBody.html.twig
  src/View/layout.html.twig
  src/utils/CleanData.php
Labels: Reviewed by PO

#68 footer
  public/assets/css/style.css
  src/View/Item/_footer.html.twig
Labels: Reviewed by PO

#58 Sprint02 us4 card
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/ProductManager.php
  src/View/Home/index.html.twig
  src/View/Item/_card.html.twig
  src/View/_card.html.twig
Labels: Reviewed by PO

#70 Sprint03 us16 ajout produit
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/add.html.twig
Labels: Reviewed by PO

#71 fix jumbotron
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#81 Sprint02 us06 notrenoutique
  composer.lock
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
Labels: Corrections done

#85 Fixes02
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_formContact.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#89 Sprint03 us20 faq
  public/assets/css/style.css
  src/Controller/FaqController.php
  src/View/Faq/index.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#87 Sprint02 us7 fonctionnementdepotvente
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#82 Sprint03 us17 nos produits
  src/Controller/HomeController.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Products/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#107 fix03_categoriesOrder
  src/Controller/AdminCategoryController.php
  src/Controller/AdminProductController.php
  src/Controller/FaqController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/Model/CategoryManager.php
Labels: Reviewed by PO

#115 Fix04_LinkOnNavbarAndFooter
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#110 Sprint03_US24_creationCategorie
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/categories.html.twig
Labels: Reviewed by PO

#116 Fix05_ReAddMethodDeletedByError
  .gitignore
  src/Model/ProductManager.php
Labels: Reviewed by PO

#90 Sprint03 us18 page produit
  public/assets/css/style.css
  public/assets/js/main.js
  src/Controller/AdminCategoryController.php
  src/Controller/ItemController.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Item/showItem.html.twig
  src/View/layout.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#121 Add selection by categories in products page
  public/assets/css/style.css
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Products/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#122 Refonte homepage
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/Item/_card.html.twig
  src/View/Item/_footer.html.twig
Labels: Reviewed by PO

#131 fix bugs on contact forms
  src/Controller/HomeController.php
  src/View/Item/_formContact.html.twig
Labels: Reviewed by PO

#129 Random items on the product page
  src/Controller/ItemController.php
  src/Model/ProductManager.php
  src/View/Item/_card.html.twig
  src/View/Item/showItem.html.twig
Labels: Reviewed by PO

#130 Fix06_design&productPage
  public/assets/css/style.css
  src/View/Item/_card.html.twig
  src/View/Item/showItem.html.twig
Labels: Reviewed by PO

#132 creation page notre produit
  src/Controller/OurStoreController.php
  src/View/Home/index.html.twig
  src/View/Item/_operationDeposit.html.twig
  src/View/Item/_ourStore.html.twig
  src/View/OurStore/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done

#133 add delete for category administration
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/categories.html.twig
Labels: Reviewed by PO

#135 fixe bugs on dropdown notre boutique
  public/assets/css/style.css
Labels: Reviewed by PO

#138 Fix09 fix links
  src/View/Home/index.html.twig
  src/View/Item/_card.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_operationDeposit.html.twig
  src/View/Item/_ourStore.html.twig
  src/View/OurStore/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#123 Sprint03 us19 recherche
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/ProductController.php
  src/Model/AbstractManager.php
  src/View/Home/index.html.twig
  src/View/Products/index.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Corrections done

#140 Favicon and title fix referencement and navbar
  public/assets/css/style.css
  public/assets/images/favicon.png
  src/View/Faq/index.html.twig
  src/View/Home/index.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/Item/showItem.html.twig
  src/View/OurStore/index.html.twig
  src/View/layout.html.twig
  src/View/visitorLayout.html.twig
Labels: Corrections done

#142 Dev
  .gitignore
  composer.json
  composer.lock
  public/assets/css/style.css
  public/assets/images/delete-filled.png
  public/assets/images/edit-filled.png
  public/assets/images/favicon.png
  public/assets/images/jumbotron-furniture.png
  public/assets/images/logo.png
  public/assets/js/main.js
  src/Controller/AbstractController.php
  src/Controller/AdminCategoryController.php
  src/Controller/AdminProductController.php
  src/Controller/FaqController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/OurStoreController.php
  src/Controller/ProductController.php
  src/Model/AbstractManager.php
  src/Model/CategoryManager.php
  src/Model/PictureManager.php
  src/Model/ProductManager.php
  src/View/Admin/add.html.twig
  src/View/Admin/categories.html.twig
  src/View/Admin/products.html.twig
  src/View/Faq/index.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_card.html.twig
  src/View/Item/_footer.html.twig
  src/View/Item/_formContact.html.twig
  src/View/Item/_operationDeposit.html.twig
  src/View/Item/_ourStore.html.twig
  src/View/Item/emailBody.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/Item/showItem.html.twig
  src/View/OurStore/index.html.twig
  src/View/Products/index.html.twig
  src/View/_adminNavbar.html.twig
  src/View/_navbar.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
  src/utils/CleanData.php
Labels: Reviewed by PO

#143 Fix11_Readd visitor layout
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#139 Sprint04 us27creationpagenotreboutique
  public/assets/css/style.css
  public/assets/images/storeimage1.jpg
  public/assets/images/storeimage2.jpg
  public/assets/images/storeimage3.jpg
  public/assets/images/storeimage4.jpg
  public/assets/images/storeimage5.jpg
  public/assets/images/storeimage6.jpg
  public/assets/images/storeimage7.jpg
  public/assets/images/storeimage8.jpg
  src/View/OurStore/index.html.twig
Labels: Reviewed by PO

#144 fix block faq
  src/View/Faq/index.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#145 Fix13 bug on navbar caused by merge
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#146 Dev
  public/assets/css/style.css
  public/assets/images/storeimage1.jpg
  public/assets/images/storeimage2.jpg
  public/assets/images/storeimage3.jpg
  public/assets/images/storeimage4.jpg
  public/assets/images/storeimage5.jpg
  public/assets/images/storeimage6.jpg
  public/assets/images/storeimage7.jpg
  public/assets/images/storeimage8.jpg
  src/View/Faq/index.html.twig
  src/View/OurStore/index.html.twig
  src/View/_navbar.html.twig
  src/View/visitorLayout.html.twig
Labels: Reviewed by PO

#152 add saled option in products form
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/Admin/add.html.twig
Labels: Reviewed by PO

#153 fix bug on categoriesAdmin
  src/View/Admin/categories.html.twig
Labels: Reviewed by PO

#156 fix bugs on showrandom method
  src/Controller/ItemController.php
  src/Model/ProductManager.php
Labels: Reviewed by PO

#157 ajout bandeau vendu
  public/assets/css/style.css
  src/Model/ProductManager.php
  src/View/Item/_card.html.twig
Labels: Reviewed by PO
